### ISSUE TITLE
Over-Clustering

### ISSUE THREAD

**Issue by YIBO-0805** [Emprime/FuzzyOverclustering#1]
Hello, I have read your paper recently and learned a lot. But I don't understand over-clustering, can you tell me more about it?

**Comment by Emprime** [comment]
Hi, Overclustering is the idea of clustering the data into more clusters than actual classes exists. For example for the plankton dataset we have 10 classes but we allow a clustering in up to 60 clusters. This overclustering allows a more fine-grained distinction of the objects. Ji et al. used the idea in https://arxiv.org/abs/1807.06653 to improve their clustering. I extended the idea in this paper especially with the loss crossentropy inverse and generalized it in the next paper https://arxiv.org/abs/2106.16209 

Does this answer your question?

**Comment by YIBO-0805** [comment]
Do normal heads and over-clustering heads work together?

**Comment by Emprime** [comment]
Yes and No, they share the same backbone while the heads itselves are individual fully connected layers.
